//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int Id { get; set; }
        public string product { get; set; }
        public Nullable<double> jumlah { get; set; }
        public string endurance { get; set; }
        public Nullable<System.DateTime> next_shipment { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
